"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _page_home from './page-home.bones.json'
import _page_about from './page-about.bones.json'
import _page_timeline from './page-timeline.bones.json'
import _page_gallery from './page-gallery.bones.json'
import _page_join from './page-join.bones.json'
import _page_404 from './page-404.bones.json'

configureBoneyard({"color":"rgba(0, 0, 0, 0.06)","darkColor":"rgba(255, 255, 255, 0.08)","animate":"shimmer","shimmerColor":"rgba(107, 70, 193, 0.15)","darkShimmerColor":"rgba(107, 70, 193, 0.3)","speed":"1.6s","stagger":true,"transition":250})

registerBones({
  "page-home": _page_home,
  "page-about": _page_about,
  "page-timeline": _page_timeline,
  "page-gallery": _page_gallery,
  "page-join": _page_join,
  "page-404": _page_404,
})
